"""removed featured

Revision ID: 11eb34e2500c
Revises: d69c1205c347
Create Date: 2024-01-14 07:27:22.639812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11eb34e2500c'
down_revision: Union[str, None] = 'd69c1205c347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_featured', table_name='articles')
    op.drop_column('articles', 'featured')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('featured', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.create_index('ix_articles_featured', 'articles', ['featured'], unique=False)
    # ### end Alembic commands ###
