"""article edit

Revision ID: d69c1205c347
Revises: 
Create Date: 2024-01-12 15:18:57.961627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69c1205c347'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('featured', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_articles_featured'), 'articles', ['featured'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_featured'), table_name='articles')
    op.drop_column('articles', 'featured')
    # ### end Alembic commands ###
