import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html>
        <Head>
            <meta name="description" content="Generated by create next app" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
            <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Inter:wght@900&family=Lateef&family=Lora:ital@1&display=swap" rel="stylesheet" />     
          </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}